name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:        # 👈 allows running the workflow manually

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      ENV_TYPE: CI
      BASE_URL: https://www.trgint.com/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # Match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Playwright tests (Chromium, Firefox, WebKit)
        run: |
          pytest -v --maxfail=1 --disable-warnings
